import type { Diagram } from "./types";

export const DISTRIBUTED_CACHE: Diagram = {
  id: "distributed-cache",
  title: "Distributed Cache",
  question: "Design a Distributed Cache (Memcached / Redis at scale)",
  sourceId: "patterns",
  itemId: 34,
  overview: {
    shape:
      "Everywhere else in this collection a cache is one box; this is the inside of that box, and it is a hint store bolted to the read path, so the hit is trivial and every component drawn here is a defence on the miss path or the invalidation path.",
    beats: [
      "The hit path is one hop and deliberately boring. The application asks its in-process L1 for the handful of allowlisted hot keys, then the tier, where the ring maps the key to one of 60 shards and RAM answers in about 0.3ms. That is 98% of 5M gets/s, and the origin never learns those reads happened.",
      "Every miss is a small write, which is why the miss path carries the machinery. One loader per key takes a short-lived lock so 10k concurrent misses become one origin query, the value goes back with a 300s TTL jittered by 10%, and a rising refresh probability near expiry means a hot key's TTL never actually arrives.",
      "The sizing is arithmetic and it justifies everything after it. A 10TB working set over 180GB shards is 60 primaries, 5M over 60 is 83k ops/s each against a 150k to 200k ceiling, and 5M x (1 - h) < 100k of origin capacity forces h > 98%. Hit rate is a capacity constraint, not a target.",
      "Sharding does not fix a hot key, because one key lives on one shard. A million reads per second of a 2KB value is 16 Gbps arriving at a single NIC while 59 shards run at 1.3 Gbps. The two fixes trade different things: the L1 cuts tier reads to P/T but makes the key uninvalidatable, key-level replication over 8 shards divides the bandwidth and keeps delete working.",
      "Invalidation is where a cache stops being a performance optimisation and starts being able to show a customer a wrong number. Writes commit to the origin and then delete the key, never overwrite it, because deletes commute and absent is always safe. A change-log consumer does the same job once instead of once per call site, and a backstop TTL bounds whatever both of them miss.",
      "Say plainly that a cache is not a database: it may lose every value at any moment and the system must still be correct. Then say the uncomfortable half, which is that an origin sized for 100k QPS against 5M reads/s cannot survive a cold pool, so availability really does depend on the cache being warm and rate-limited fill is a degradation, not a fix.",
    ],
    crux:
      "Two things have to be true at once. The cache may lose any value at any moment with no correctness consequence, and it may not serve a wrong value for an unbounded time. Hold only the first and the cache is free in your head and you ship a price that changed twenty minutes ago. Hold only the second and you reach for persistence and quorum reads and rebuild a slow database that happens to live in RAM.",
    numbers: [
      "5M gets/s, so h > 98% is arithmetic",
      "60 shards x 180GB for a 10TB working set",
      "one hot key = 16 Gbps on one NIC",
    ],
  },
  nodes: [
    {
      id: "tier-group",
      label: "Cache tier: 60 shards, ~30TB RAM, nothing durable",
      kind: "zone",
      x: 24,
      y: 404,
      w: 672,
      h: 208,
      detail: {
        what: "The cache cluster itself: 60 primary shards with one replica each, holding a 10TB working set entirely in RAM with persistence switched off.",
        why: "Everything in this box is derived state. Disaster recovery is refilling from the origin rather than restoring anything, which is what makes the tier cheap to run and what makes invalidation the only hard problem it has.",
        numbers: ["120 processes x 256GB = ~30TB provisioned", "10TB working set, corpus is 10x larger", "RPO is not applicable, nothing here is authoritative"],
        breaks:
          "The tier is allowed to be empty and is not allowed to be wrong, and the second property is not enforced by anything inside this box.",
      },
    },
    {
      id: "app",
      label: "App server",
      sub: "cache aside, 5 gets per request",
      kind: "service",
      x: 40,
      y: 0,
      w: 280,
      detail: {
        what: "The tier that owns the caching logic: read the cache, load the origin on a miss, write the value back, and delete the key after a write.",
        why: "The cache has no idea which origin row a key came from or when it changed, so read, fill and invalidate decisions all live here. At a 100:1 read to write ratio, putting the cache in the write path would change nothing for 99% of operations.",
        numbers: ["10k app servers x 100 req/s x 5 gets = 5M gets/s", "50k writes/s, a 100:1 ratio", "cache timeout above 5ms is counted as a miss"],
        breaks:
          "A request that blocks waiting on a slow cache turns a cache incident into an application outage. Above 5ms, treat it as a miss, count it, and go to the origin.",
        choice: {
          pick: "Cache aside on reads; on writes commit to the origin then delete the key",
          instead: "Write-through, where the cache writes the origin and acks only when both commit; or write-behind, where the cache acks immediately and drains a queue.",
          decider: "The 100:1 ratio. At 5M reads/s against 50k writes/s, write-through adds a hop and a failure mode to 1% of operations, changes nothing for the other 99%, and caches values nobody has asked for. Write-behind at a 200ms flush interval loses up to 10,000 acknowledged writes on a crash.",
          flips: "Below roughly 10:1, especially where the same key is written repeatedly. Write-behind genuinely wins for counters, view tallies and telemetry, where writes are dense, repeated on one key and individually worthless.",
        },
      },
    },
    {
      id: "l1",
      label: "In-process L1",
      sub: "hot-key allowlist, 100ms to 1s TTL",
      kind: "service",
      x: 40,
      y: 100,
      w: 280,
      detail: {
        what: "A per-process copy of an explicitly allowlisted set of hot keys, held for 100ms to 1s and checked before the tier.",
        why: "Reads reaching the cache tier for one key fall to P/T, where P is the process count and T the L1 TTL. At P = 10k and T = 1s that is 10k/s instead of 1M/s, which takes a hot key from 16 Gbps on one NIC to 160 Mbps.",
        numbers: ["P/T = 10k/1s = 10k reads/s at the tier", "a 100x cut on the hot key", "staleness floor becomes T"],
        breaks:
          "No delete can reach 10,000 process heaps, so putting an L1 in front of a key silently converts that key's invalidation into a TTL.",
        choice: {
          pick: "An explicit allowlist of hot keys with a sub-second TTL, never a blanket L1",
          instead: "Key-level replication: store the value across 8 shards under suffixed names and pick a suffix at random per read.",
          decider: "The staleness budget against the fanout arithmetic. P/T only buys anything while T exceeds the budget: at P = 100k with T = 100ms, P/T is 1M/s and the L1 has bought nothing at all.",
          flips: "Anything gating money or access, such as prices, entitlements, feature flags and rate limit state. Those must stay invalidatable, so they get the 8-way replication instead, at 8 SETs per fill and 8 deletes per invalidation.",
        },
      },
    },
    {
      id: "proxy",
      label: "Proxy tier",
      sub: "~200 proxies, 4 conns per shard",
      kind: "service",
      x: 40,
      y: 200,
      w: 280,
      detail: {
        what: "A fleet that multiplexes application connections onto a few hundred backend connections per shard and owns the topology on behalf of every client.",
        why: "Connection count is a real constraint before throughput is. It also gives one place to change the shard map without redeploying 10k application servers, which is what makes a resize an operation rather than a release.",
        numbers: ["1.2M sockets direct vs ~800 per shard behind proxies", "20k sockets/shard x 20KB = 400MB of buffers", "extra hop of 100 to 500 microseconds"],
        breaks:
          "It is a new component that can fail, so it needs enough instances that losing one is not a thundering reconnect across the whole fleet.",
        choice: {
          pick: "A proxy tier between the applications and the shards",
          instead: "A client library with the ring compiled in, talking straight to the shards.",
          decider: "Sockets against latency budget. 10k app servers x 60 shards x 2 connections is 1.2M sockets, 20k per shard; proxies cut that to 800 per shard and cost 100 to 500 microseconds against a sub-1ms p99.",
          flips: "Small fleets, where 1.2M never materialises and the hop is pure cost, or a budget tight enough that half a millisecond matters. Then the in-process client library wins and topology changes become a deploy.",
        },
      },
    },
    {
      id: "ring",
      label: "Consistent hash ring",
      sub: "~150 vnodes per shard, 60 shards",
      kind: "service",
      x: 40,
      y: 300,
      w: 280,
      detail: {
        what: "The function mapping a key to its owning shard, with roughly 150 virtual positions per physical shard. Q2 is the ring itself in full; here it is one lookup on the hot path.",
        why: "The placement decision is load-bearing for the cache specifically because a remap is a miss burst. Hashing modulo the node count empties the cache on every resize and hands the full read load to an origin sized for 2% of it.",
        numbers: ["adding a shard moves ~1/60 of the keyspace", "modulo remaps ~98% of keys", "1 position per shard gives 2x to 3x imbalance"],
        breaks:
          "Even the 1/N that legitimately moves arrives at the origin as a miss burst, so a resize stays a scheduled event rather than a free one.",
        choice: {
          pick: "Consistent hashing with ~150 virtual positions per shard",
          instead: "hash(key) modulo the node count, or a shard map maintained centrally and pushed to clients.",
          decider: "What a resize costs. Modulo remaps about 98% of 5B keys and sends 5M reads/s at a 100k QPS origin; the ring moves 1/60. Virtual nodes are the second half: 1 position per shard gives 2x to 3x imbalance, 150 brings it into low single-digit percent.",
          flips: "A cluster whose shard count genuinely never changes, where an explicit map is easier to reason about and to override for a deliberately placed key class.",
        },
      },
    },
    {
      id: "shard",
      label: "Cache shard",
      sub: "Redis, 180GB maxmemory, persistence off",
      kind: "database",
      x: 40,
      y: 420,
      w: 280,
      detail: {
        what: "One single-threaded in-memory shard holding about 1/60 of the working set and answering GET and SET in well under a millisecond.",
        why: "The shard count falls straight out of memory: 10TB over 180GB usable is 56, rounded to 60. The per-shard rate then falls out of that, and the ~2x headroom is what absorbs one shard inheriting a dead peer's traffic.",
        numbers: ["83k ops/s per shard against a 150k to 200k ceiling", "1.3 Gbps per shard, trivial on 25 GbE", "maxmemory 180GB = 70% of a 256GB box"],
        breaks:
          "Turning on persistence for warm restarts is the trap: the fork's copy on write can double the process at exactly the moment memory is tight, and it restores values written under an invalidation regime that was not running during the restart.",
        choice: {
          pick: "Redis Cluster, 60 primaries at 180GB maxmemory, persistence off",
          instead: "Memcached: flat string to string, multi-threaded, with no persistence or replication primitive at all.",
          decider: "Which features are needed, not which is faster. Redis buys hashes, sorted sets and native replication; Memcached buys a simpler failure model and implements leases natively where Redis needs a Lua script plus a second key. Both cap at 70% of RAM so fragmentation, client buffers and any fork have somewhere to live.",
          flips: "When plain string values genuinely are all you need. Then Memcached's multi-threading and its complete absence of durability machinery are an advantage rather than a gap.",
        },
      },
    },
    {
      id: "eviction",
      label: "TTL + eviction",
      sub: "LRU + backstop TTL, jittered 10%",
      kind: "service",
      x: 440,
      y: 420,
      w: 240,
      detail: {
        what: "Two different mechanisms that both remove data: a TTL that bounds how stale a value can be, and eviction that decides who survives a full memory cap.",
        why: "They answer separate questions and only one of them is usually binding. Residency here is 10TB over 200 MB/s of churn, about 14 hours, so against a 300s median TTL keys expire long before eviction ever reaches them and the policy fork can be skipped.",
        numbers: ["residency ~14 hours vs a 300s median TTL", "100k admissions/s = 200 MB/s of churn", "expiry metadata 24B x 5B keys = ~120GB"],
        breaks:
          "At the memory cap a node either evicts or dies, and the default in most deployments is that keys without a TTL are not evictable, which quietly turns a memory cap into an out-of-memory kill.",
        choice: {
          pick: "LRU with a backstop TTL on every key, jittered by 10%",
          instead: "An admission policy in front of the cache: W-TinyLFU (2015) with a frequency sketch, or S3-FIFO (SOSP 2023) with a small probationary queue and no sketch.",
          decider: "The share of admissions evicted having been read exactly once. Below about 20% one-hit wonders LRU is fine; above about 50%, half of a 10TB cache is holding keys nobody will read again and admission control recovers that space directly.",
          flips: "Workloads that sweep a key range once: search result caches, feed backfills, analytics jobs and crawler traffic. A single nightly batch can flush a day of warm state through LRU in minutes, and a bigger cache does not help.",
        },
      },
    },
    {
      id: "replica",
      label: "Async replica",
      sub: "one per shard, ~10s promotion",
      kind: "database",
      x: 440,
      y: 530,
      w: 240,
      detail: {
        what: "One asynchronous replica per primary, promoted on failure and optionally serving reads to multiply read capacity.",
        why: "Without a replica, losing a node deletes 1/60 of the keyspace permanently and hands the origin that shard's miss traffic. Surviving nodes do not inherit the dead node's data, because consistent hashing reassigns ownership rather than moving bytes.",
        numbers: ["failover in roughly 10s", "one dead shard = 83k QPS into a 100k origin", "replica lag stacks on top of the TTL"],
        breaks:
          "A replica can return a value the primary has already deleted, so the bound you publish for replica reads is the TTL plus the lag, not the larger of the two.",
        choice: {
          pick: "One async replica per shard, with tight-budget key classes routed to the primary",
          instead: "No replica at all, letting the origin absorb a dead shard; or synchronous replication so a promoted replica never lags.",
          decider: "What the origin can absorb. One dead shard is 83k QPS against 100k of total capacity, survivable once and not twice, which is the argument for a replica and for placing it in a different failure domain. Synchronous replication puts a round trip on a sub-1ms write path for data nobody is allowed to depend on.",
          flips: "When the origin is genuinely over-provisioned against the read load, where replicas are pure cost: the cache is derived state and the correct recovery is a refill.",
        },
      },
    },
    {
      id: "hotkey",
      label: "Hot key detection",
      sub: "sampled heavy hitters, ~10s window",
      kind: "service",
      x: 440,
      y: 100,
      w: 240,
      detail: {
        what: "Per-shard egress plus sampled per-key request counts, feeding the L1 allowlist and the decision to replicate a key across shards.",
        why: "Both hot key mitigations assume you know which key is hot, and nothing here does by default. Exact per-key counters at 5M ops/s are not affordable, so detection is sampled or a heavy hitters sketch over a window long enough to trust.",
        numbers: ["detection lag on the order of 10s", "a key can reach 1M reads/s inside that window", "16 Gbps on one NIC vs 1.3 Gbps per shard"],
        breaks:
          "Detection lags the hot key, so the first seconds of every hot key are served with no mitigation at all and the owning shard saturates before anything engages.",
        choice: {
          pick: "Sampled server-side heavy hitters plus a manual promotion path for predictable keys",
          instead: "Client-side detection inside each application process, or exact per-key counters at the shard.",
          decider: "Cost against reaction time. Exact counters at 5M ops/s are unaffordable. Client-side detection reacts immediately because a process sees its own repeated reads, but each of 10k processes sees only its slice and a fleet-hot key can be lukewarm in every one of them.",
          flips: "Predictable hot keys, such as a scheduled drop or a launch, where a manual allowlist beats every detector because it engages before the traffic arrives rather than 10 seconds into it.",
        },
      },
    },
    {
      id: "loader",
      label: "Single-flight loader",
      sub: "per-key lock, early refresh, TTL jitter",
      kind: "service",
      x: 40,
      y: 620,
      w: 280,
      detail: {
        what: "The miss path: the first request to detect a miss takes a short-lived per-key lock, queries the origin, populates the cache and releases, while everyone else waits and reads what it wrote.",
        why: "Three defences layered because each leaves a gap the others cover. One loader per key limits the damage of an expiry; probabilistic refresh before expiry and jittered TTLs stop expiries being synchronised in the first place.",
        numbers: ["10k concurrent misses collapse to 1 origin query", "set 3600 + random 0 to 360, never exactly 3600", "10M actively read keys on a 300s TTL = 33k refreshes/s"],
        breaks:
          "None of the three helps with a cache that starts empty. A cold pool has the same symptom as a stampede and a completely different cause, which is why it needs a rate limiter instead.",
        choice: {
          pick: "A per-key lock built on the cache itself, with no consensus and no fencing token",
          instead: "A real lock service with consensus and monotonic fencing tokens (Q35), or no coordination at all.",
          decider: "What a lost grant costs: one duplicate origin query, against a 100k QPS budget. Paying tens of milliseconds for consensus to protect a single extra read would destroy the only reason the cache exists.",
          flips: "Never for this lock, and that is the point worth saying out loud. The moment the protected thing is a mutation rather than a read, a lost grant corrupts data and this construction is wrong.",
        },
      },
    },
    {
      id: "origin",
      label: "Origin database",
      sub: "50 read replicas, 100k QPS ceiling",
      kind: "database",
      x: 40,
      y: 740,
      w: 280,
      detail: {
        what: "The only authoritative copy of the data. Every miss and every fill lands here, and every write commits here first.",
        why: "This number sets the required hit rate rather than the other way round. 5M x (1 - h) < 100k gives h > 98%, so each point of hit rate is 50k QPS and a key format change is a capacity change.",
        numbers: ["50 replicas x 2k QPS = 100k QPS available", "h > 98%; at 97% the origin is 50% over", "~20ms per row read vs ~0.3ms cached"],
        breaks:
          "Cold start. The origin is sized for 1/50th of peak read load, so an empty pool presents it with 50x its capacity and it saturates long before the cache can refill.",
        choice: {
          pick: "Size the origin for misses and protect it with rate-limited fill and load shedding",
          instead: "Size the origin for the real read load, or turn on cache persistence so restarts come back warm.",
          decider: "Cost and honesty. 5M QPS of origin capacity is 50x the 100k actually bought, and persistence does not close the gap either: it restores values whose freshness cannot be reasoned about and adds a fork under memory pressure.",
          flips: "When the working set is small enough that the origin can serve peak unaided. Then the cache really is only a latency optimisation and losing it is genuinely free, which is the claim everyone makes and few can support.",
        },
      },
    },
    {
      id: "writer",
      label: "Write path",
      sub: "commit, then DELETE, never SET",
      kind: "service",
      x: 440,
      y: 740,
      w: 240,
      detail: {
        what: "The 50k writes/s path. It commits to the origin first and then deletes the cache key rather than overwriting it.",
        why: "Only one of four orderings survives. Delete first and a reader caches the pre-write value inside the commit window. Overwrite after committing and two writers can apply SETs in the opposite order to their commits. Deletes commute, and absent is always safe.",
        numbers: ["50k writes/s, 1% of reads", "delete-first window = the origin write, single-digit ms", "at 100k misses/s a 1-in-1M race poisons a key every 10s"],
        breaks:
          "Commit-then-delete still loses to a stalled reader: it reads v1, a writer commits v2 and deletes nothing because the key is absent, then the reader SETs v1, which survives the full TTL.",
        choice: {
          pick: "Commit then DELETE, with a backstop TTL on every key without exception",
          instead: "Versioned values, where a SET carrying an older row version or LSN is rejected; or leases, where a DELETE invalidates the reader's outstanding token (Facebook memcache, NSDI 2013).",
          decider: "Whether the stalled-reader race must be closed or merely bounded. Versioning costs 8B per value, 40GB across 5B keys, and turns every SET into a compare-and-set. Leases stop the cache being a plain key-value store. A TTL costs nothing and is the only bound that does not depend on another system being reachable.",
          flips: "Key classes with a tight staleness budget, or anything gating money. Leases are the better buy of the two there, because one lease per key per interval is also the stampede defence for free.",
        },
      },
    },
    {
      id: "invalidator",
      label: "Change-log invalidator",
      sub: "CDC consumer + cross-region delete",
      kind: "queue",
      x: 440,
      y: 860,
      w: 240,
      detail: {
        what: "A consumer of the origin's committed change stream that deletes the affected keys, and broadcasts those deletes to the other regions' independent pools.",
        why: "It gives one implementation of invalidation ordered by the store's own commit ordering, instead of a hand-written delete at every call site where one forgotten delete is a stale value that lives until its TTL.",
        numbers: ["propagation lag becomes the published staleness bound", "delete broadcast is negligible in bytes", "a dropped broadcast is invisible, so the TTL is the real guarantee"],
        breaks:
          "It cannot name derived keys. A page fragment built from a user row, a settings row and three feed rows has no key a row-level event can name, so that class gets a short TTL and no invalidation at all.",
        choice: {
          pick: "Drive deletes off the origin's change log, with best-effort broadcast between per-region pools",
          instead: "Every write path issuing its own DELETE, or a tag index mapping source rows to the derived keys built from them.",
          decider: "How many services write the same tables. Past roughly 3 or 4 writers of a table, hand-written deletes get forgotten somewhere and the 300s backstop TTL becomes the actual guarantee. A tag index grows without bound and Redis does not implement one, so it is a second cache with the same problem one level down.",
          flips: "A single service owning every write to a table, where an inline delete is one line of code and a CDC pipeline is an entire system to operate for nothing.",
        },
      },
    },
  ],
  edges: [
    {
      id: "e1",
      from: "app",
      to: "l1",
      label: "hot-key allowlist first",
      animated: true,
      detail: {
        what: "The read checking the process-local copy before anything leaves the machine, for the small allowlisted set of keys that have one.",
        why: "It exists only for keys whose fanout would otherwise land on one NIC. Every other key skips it, because a blanket L1 would make the whole keyspace uninvalidatable to buy nothing measurable.",
        numbers: ["allowlisted keys only", "100ms to 1s TTL"],
        breaks: "If the allowlist grows by accident, key classes silently acquire a staleness floor nobody chose and no delete can reach.",
      },
    },
    {
      id: "e2",
      from: "l1",
      to: "proxy",
      label: "GET, 5M/s fleet-wide",
      animated: true,
      detail: {
        what: "The actual cache read leaving the application process on a pooled connection to the proxy tier.",
        why: "This is the hop the whole system is sized around: 5M gets/s at a sub-1ms p99, which is why it is a pooled binary protocol rather than anything that opens a connection per call.",
        numbers: ["5M gets/s peak", "p99 under 1ms including the network hop"],
        breaks: "Above a 5ms timeout the caller must give up and treat it as a miss; waiting on a degraded cache is how a cache incident becomes an outage.",
      },
    },
    {
      id: "e3",
      from: "proxy",
      to: "ring",
      label: "route by key",
      detail: {
        what: "The proxy resolving which shard owns the key, using the ring it holds rather than asking anyone.",
        why: "Placement has to be a local computation on a sub-millisecond path. Holding it in the proxy rather than in 10k clients is what lets the topology change without a fleet-wide redeploy.",
        numbers: ["one binary search, no network hop"],
        breaks: "A proxy on a stale ring routes confidently to the wrong shard, which shows up as a miss rather than an error and quietly costs origin capacity.",
      },
    },
    {
      id: "e4",
      from: "ring",
      to: "shard",
      label: "owning shard of 60",
      animated: true,
      detail: {
        what: "The GET arriving at the single shard that owns this key.",
        why: "One key has exactly one owner, which is what makes the cache cheap and is also the entire hot key problem: no amount of sharding splits the load for a key that 1M requests per second all want.",
        numbers: ["83k ops/s per shard in aggregate", "1M reads/s if they all want one key"],
        breaks: "A single key can saturate its owner's NIC at 16 Gbps while the other 59 shards sit at 1.3 Gbps, and the routing layer cannot help.",
      },
    },
    {
      id: "e5",
      from: "shard",
      to: "app",
      label: "hit: ~0.3ms, 98%",
      animated: true,
      fromSide: "left",
      toSide: "left",
      offset: 90,
      detail: {
        what: "The hit path returning a ~2KB value, which is where 98% of the 5M gets/s end.",
        why: "This arrow is the entire reason the system exists and it is also the least interesting one. On a hit the origin never learns the read happened, which is what turns 5M reads/s into 100k.",
        numbers: ["~0.3ms vs ~20ms at the origin", "98% of reads end here"],
        breaks: "Nothing on this path is authoritative, so a value returned here can be stale by up to the TTL, plus replication lag if it came from a replica.",
      },
    },
    {
      id: "e6",
      from: "shard",
      to: "loader",
      label: "miss: 100k/s",
      animated: true,
      detail: {
        what: "A miss handed to the loader, which is the only path allowed to touch the origin.",
        why: "Misses are a capacity number rather than an error: at 99% they are 50k/s and half the origin is spare, at 97% they are 150k/s and the origin is 50% over. Routing them through one place is what makes them countable and limitable.",
        numbers: ["5M x 2% = 100k misses/s", "each is also an admission, 200 MB/s of churn"],
        breaks: "A miss storm is indistinguishable from normal traffic at the shard, so the alarm has to live on origin QPS rather than on the cache.",
      },
    },
    {
      id: "e7",
      from: "loader",
      to: "origin",
      label: "1 loader per key",
      animated: true,
      detail: {
        what: "The origin query, made by exactly one holder of the per-key lock while every other misser waits.",
        why: "Without it, one popular key expiring turns 10 QPS into 10,000 in the same millisecond. The lock is what converts a stampede into a single read plus a short wait for everyone else.",
        numbers: ["10k concurrent misses become 1 query", "~20ms per origin read"],
        breaks: "If the loader dies holding the lock, every waiter stalls until it expires, so the lock TTL directly bounds the latency of a miss on a hot key.",
      },
    },
    {
      id: "e8",
      from: "loader",
      to: "shard",
      label: "SET, TTL 300s +/-10%",
      fromSide: "left",
      toSide: "left",
      offset: 40,
      detail: {
        what: "The fill: writing the loaded value back with a jittered TTL, which is why every miss is also a small write.",
        why: "Jitter is the cheap half of the stampede defence. Keys written in the same batch and given exactly 3600 seconds will expire in the same millisecond and rediscover each other at the origin.",
        numbers: ["3600 + random 0 to 360", "100k admissions/s in steady state"],
        breaks: "This is the SET a stalled reader makes with a superseded value, which is the invalidation race that a backstop TTL bounds and only versioning or leases actually closes.",
      },
    },
    {
      id: "e9",
      from: "shard",
      to: "eviction",
      label: "180GB cap, TTL sweep",
      dashed: true,
      fromSide: "right",
      toSide: "left",
      detail: {
        what: "The two mechanisms inside the shard that remove data: expiry sweeping keys past their TTL, and eviction reclaiming under the memory cap.",
        why: "It is drawn as a control path because it removes data rather than serving it, and because which of the two is actually binding decides whether the eviction policy fork is worth any time at all.",
        numbers: ["residency ~14 hours vs 300s median TTL", "evictions/s is the metric that says which one binds"],
        breaks: "If keys without a TTL are configured as non-evictable, the cap stops being a cap and the process is OOM killed instead.",
      },
    },
    {
      id: "e10",
      from: "shard",
      to: "replica",
      label: "async replication",
      dashed: true,
      fromSide: "right",
      toSide: "left",
      offset: 40,
      detail: {
        what: "Asynchronous replication of the primary's writes to its replica, which stands ready for promotion and can serve reads.",
        why: "It is deliberately asynchronous. Making it synchronous would put a network round trip on a sub-1ms write path in order to durably preserve data that is by definition allowed to vanish.",
        numbers: ["promotion in roughly 10s", "lag is a second staleness source on top of the TTL"],
        breaks: "A replica serving reads can return a value the primary has already deleted, for as long as the lag lasts, which is fine for a profile blob and not for an entitlement.",
      },
    },
    {
      id: "e11",
      from: "shard",
      to: "hotkey",
      label: "sampled per-key counts",
      dashed: true,
      fromSide: "right",
      toSide: "bottom",
      offset: 60,
      detail: {
        what: "Per-shard egress and sampled request counts flowing to the detector that decides which keys are hot.",
        why: "Egress per node is cheap and exact but tells you a shard is saturated, not which key did it. Sampled key counts answer the second question at a cost that does not scale with 5M ops/s.",
        numbers: ["per_shard_egress_gbps plus sampled counts", "trustworthy window ~10s"],
        breaks: "The window that makes the sample trustworthy is the same window during which the shard is already saturated and nothing has engaged.",
      },
    },
    {
      id: "e12",
      from: "hotkey",
      to: "l1",
      label: "promote to L1 allowlist",
      dashed: true,
      fromSide: "left",
      toSide: "right",
      detail: {
        what: "A detected hot key being added to the allowlist that application processes cache locally.",
        why: "This is the cheap mitigation and it is one-way in a way worth stating: adding a key here caps its tier load at P/T and simultaneously sets its staleness floor at T, with no path back for a delete.",
        numbers: ["1M/s at the tier becomes 10k/s", "staleness floor becomes the L1 TTL"],
        breaks: "Promoting a key whose value gates money or access converts a hard invalidation guarantee into a TTL without anything failing or logging.",
      },
    },
    {
      id: "e13",
      from: "hotkey",
      to: "ring",
      label: "or spread :0-:7 over 8",
      dashed: true,
      fromSide: "bottom",
      toSide: "right",
      detail: {
        what: "The other mitigation: storing the hot value under 8 suffixed names so reads pick a suffix at random and land on 8 different shards.",
        why: "It is the answer when the value must stay invalidatable. Splitting one key over 8 shards divides 16 Gbps into 2 Gbps each and keeps DELETE working, which the L1 cannot do at any TTL.",
        numbers: ["16 Gbps becomes 8 x 2 Gbps", "8 SETs per fill, 8 deletes per invalidation"],
        breaks: "The fanout is manual: every writer must remember all 8 suffixes, and a delete that misses one leaves a stale copy that one read in eight will see.",
      },
    },
    {
      id: "e14",
      from: "writer",
      to: "origin",
      label: "commit v2 first",
      fromSide: "left",
      toSide: "right",
      detail: {
        what: "The write committing to the authoritative store before anything touches the cache.",
        why: "Ordering is the whole point. Touching the cache first opens a window, single-digit milliseconds long, in which any reader misses, reads the pre-write value and caches it, and on a hot key that window is a certainty rather than a risk.",
        numbers: ["50k writes/s", "the window is the origin write duration"],
        breaks: "If the commit succeeds and the process dies before the delete, the stale key survives until its backstop TTL, which is exactly why the TTL is not optional.",
      },
    },
    {
      id: "e15",
      from: "writer",
      to: "shard",
      label: "then DELETE, never SET",
      dashed: true,
      fromSide: "left",
      toSide: "right",
      offset: 100,
      detail: {
        what: "The invalidation itself: remove the key rather than overwrite it with the new value.",
        why: "Deletes commute, so any interleaving of two of them leaves the key absent and absent is always safe. Two SETs from two writers can land in the opposite order to their commits and leave the older value resident until the TTL.",
        numbers: ["a delete on an absent key is a no-op", "idempotent, so retries are free"],
        breaks: "A delete is only as good as its fanout: it must reach the primary, every read replica, every region's pool and every process L1, and the last of those is unreachable by construction.",
      },
    },
    {
      id: "e16",
      from: "origin",
      to: "invalidator",
      label: "committed change log",
      dashed: true,
      fromSide: "bottom",
      toSide: "left",
      detail: {
        what: "The origin's committed change stream feeding the invalidation consumer.",
        why: "Reading the log rather than trusting writers gives one implementation of invalidation with the store's own commit ordering, and nothing is forgotten because nothing is hand-written per call site.",
        numbers: ["ordering is the store's commit ordering", "the consumer's lag is the staleness bound you publish"],
        breaks: "Consumer lag is a staleness bound that nobody sees fail: reads keep succeeding, they are just answering from before the write.",
      },
    },
    {
      id: "e17",
      from: "invalidator",
      to: "shard",
      label: "delete the row's keys",
      dashed: true,
      fromSide: "right",
      toSide: "right",
      offset: 150,
      detail: {
        what: "Deletes derived from committed row changes, applied to this region's pool and broadcast to the others.",
        why: "It removes the requirement that every one of many services remembers to invalidate. Cross-region it is best effort by construction, because there is no acknowledgement worth waiting on without making a local write depend on a remote region.",
        numbers: ["negligible bytes on the wire", "the backstop TTL remains the only real guarantee"],
        breaks: "It can only delete keys a row-level event can name, so derived keys, which are the ones users actually look at, are quietly the stalest thing in the system.",
      },
    },
  ],
};
