/**
 * Terms the diagrams use without stopping to explain them. The panel underlines
 * any of these and shows the one-line definition on hover or tap, so the
 * vocabulary of the solution is kept and never assumed.
 *
 * Rules for an entry: one sentence, plain English, says what the thing IS and
 * the one fact about it the diagram leans on. Products are named as "X, a Y".
 * Keys are matched whole-word; acronyms are case-sensitive, words are not.
 *
 * The gate warns when an all-caps token or a listed product name appears in a
 * spec and is not here.
 */
export const GLOSSARY: Record<string, string> = {
  // --- consistency, replication, coordination ---
  CAS: "compare-and-set: write only if the current value is what you last read, so two concurrent writers cannot both win",
  "compare-and-swap": "an atomic write that succeeds only if the value is still what you expected; the basis of lock-free updates",
  "optimistic concurrency": "read a version number, do the work, write only if the version has not changed; retry on conflict instead of locking",
  quorum: "a majority of replicas; a write acknowledged by a quorum and a read from a quorum always overlap on at least one replica",
  "W + R > N": "with N replicas, a write acknowledged by W and a read from R overlap when W + R exceeds N, so the read sees the latest acknowledged write",
  linearizable: "every operation appears to happen at one instant between its start and its end, as if there were a single copy",
  "read-your-writes": "a client always sees its own previous writes, even if other clients might not yet",
  "last-writer-wins": "on conflict, keep the write with the latest timestamp and silently drop the other",
  LWW: "last-writer-wins: on conflict keep the write with the latest timestamp and drop the other",
  "hinted handoff": "when a replica is down, another node stores the write with a hint and forwards it when the replica returns",
  "sloppy quorum": "a quorum counted over whichever nodes are up, not the designated replicas, trading consistency for availability",
  "read repair": "when a read finds replicas disagreeing, write the newest value back to the stale ones",
  "anti-entropy": "a background process that compares replicas (often with a Merkle tree) and repairs differences",
  "Merkle tree": "a tree of hashes where each parent hashes its children, so two replicas can find where they differ by comparing a few hashes",
  "version vector": "a per-replica counter set attached to a value, used to tell whether two versions are ordered or concurrent",
  sibling: "one of two concurrent versions of a value that neither replica can order; the application has to merge them",
  tombstone: "a marker recording that a key was deleted, kept so a stale replica cannot resurrect the value",
  "gc_grace_seconds": "how long a tombstone is kept before compaction removes it; a replica down longer than this can resurrect deleted data",
  Raft: "a consensus protocol: a leader replicates a log to a majority before acknowledging, and a new leader is elected when it fails",
  Paxos: "the original consensus protocol for agreeing on a value across unreliable nodes; Raft is a more teachable equivalent",
  consensus: "a protocol by which a group of nodes agrees on one value or order even when some nodes fail",
  "two-phase commit": "a coordinator asks every participant to prepare, then tells all to commit; blocks if the coordinator dies mid-way",
  "2PC": "two-phase commit: prepare on every participant, then commit everywhere; blocks if the coordinator dies mid-way",
  XA: "the standard interface for two-phase commit across databases and queues; almost no payment provider supports it",
  saga: "a sequence of local transactions across services where each step has a compensating action to undo it on failure",
  compensation: "the action that undoes an earlier saga step (refund, release, cancel) when a later step fails",
  TCC: "try-confirm-cancel: reserve resources first, then confirm or cancel every reservation in a second round",
  idempotent: "safe to apply more than once; a retry produces the same result as the first attempt",
  "idempotency key": "a client-chosen id sent with a request so a retry is recognised and not executed twice",
  "at-least-once": "every message is delivered, possibly more than once; the consumer must tolerate duplicates",
  "at-most-once": "a message is delivered once or not at all; nothing is retried",
  "exactly-once": "each message takes effect once; in practice at-least-once delivery plus deduplication by the consumer",
  "transactional outbox": "write the event into the same database transaction as the data, then a relay publishes it, so the two cannot disagree",
  outbox: "a table written in the same transaction as the business data, drained by a relay into the message bus",
  CDC: "change data capture: reading a database's own write log and publishing every change as an event",
  Debezium: "a change-data-capture tool, a connector that streams a database's write log into Kafka",
  WAL: "write-ahead log: every change is appended to a sequential log before the main structure is updated, so a crash can be replayed",
  fsync: "the call that forces written data from the OS cache onto the disk; nothing is durable until it returns",
  "fencing token": "a monotonically increasing number issued with each lock grant; a store rejects writes carrying an older token than it has seen",
  lease: "a lock or ownership grant with an expiry; the holder must renew it and it lapses on its own if the holder dies",
  "keep-alive": "a periodic renewal that keeps a lease or connection from expiring",
  "stop-the-world": "a garbage-collection pause during which the whole process does nothing, sometimes for seconds",
  "leader election": "the process by which a group of nodes chooses one to act on behalf of the others",
  epoch: "a number that increases every time membership or leadership changes; stale participants are recognised by an old epoch",
  "split brain": "two nodes both believing they are the leader, each accepting writes the other does not see",
  "phi-accrual": "a failure detector that reports a suspicion level from the history of heartbeat delays rather than a fixed timeout",
  gossip: "each node periodically exchanges its view of membership with a few random peers until everyone converges",
  etcd: "a strongly consistent key-value store built on Raft, used for leases, leader election and configuration",
  ZooKeeper: "a coordination service (leases, locks, membership) built on a consensus log; etcd's older equivalent",
  "ephemeral node": "a ZooKeeper entry that disappears when the session that created it ends; the basis of its locks",
  czxid: "the ZooKeeper transaction id assigned when a node was created; monotonic, so it serves as a fencing token",
  mod_revision: "etcd's per-key modification counter; monotonic, so it serves as a fencing token",
  Redlock: "a Redis multi-instance locking algorithm; criticised because it depends on bounded clock drift and offers no fencing token",
  SETNX: "the Redis command set-if-not-exists, the simplest lock primitive; it offers no fencing token",
  "SET NX EX": "Redis: set the key only if absent and give it an expiry, in one atomic command",
  // --- storage ---
  LSM: "log-structured merge tree: writes go to an in-memory table and are flushed as sorted files that are merged later; fast writes, reads touch several files",
  memtable: "the in-memory sorted table an LSM store writes into before flushing it to disk",
  SSTable: "sorted string table: an immutable sorted file flushed from a memtable; reads may check several",
  compaction: "merging SSTables into fewer, larger ones to bound read amplification and drop overwritten values",
  "write amplification": "how many bytes actually hit disk per byte written, after logs, compaction and index updates",
  "Bloom filter": "a tiny probabilistic set: it can say 'definitely not present' or 'probably present', never a false negative",
  "false positive": "the filter says present when it is not; a Bloom filter's only kind of error",
  "cuckoo filter": "a Bloom-like filter that also supports deletion, at a slightly higher cost",
  RocksDB: "an embedded LSM key-value store, a library rather than a server",
  "B-tree": "the balanced on-disk tree most relational databases index with; updates in place, reads in a few page fetches",
  "page cache": "the operating system's cache of file contents in RAM; a read that hits it never touches the disk",
  mmap: "mapping a file into memory so reads become memory accesses served from the page cache",
  NVMe: "the modern SSD interface; hundreds of thousands of random operations per second per drive",
  IOPS: "input/output operations per second, the unit for random disk throughput",
  "erasure coding": "splitting data into k fragments plus m parity fragments so any k of the k+m rebuild it; less space than replication",
  "Reed-Solomon": "the standard erasure code; RS(6,3) makes 9 fragments of which any 6 rebuild the data",
  "RS(6,3)": "a Reed-Solomon code: 6 data fragments plus 3 parity, any 6 of the 9 rebuild the object, 1.5x storage overhead",
  "RF=3": "replication factor 3: every piece of data is stored on three nodes",
  "RF 3": "replication factor 3: every piece of data is stored on three nodes",
  "content-addressed": "stored and referenced by the hash of its own bytes, so identical content is stored once and cannot be silently changed",
  "wide-column": "a store like Cassandra or Bigtable: rows grouped by partition key, sorted by clustering key, sparse columns",
  Cassandra: "a wide-column, leaderless replicated store; tunable consistency, partition key routing, LSM storage",
  Scylla: "a C++ rewrite of Cassandra with the same data model",
  columnar: "stored column by column rather than row by row, so analytics that touch few columns read little data",
  Parquet: "the standard columnar file format for analytics; compresses well, reads only the columns asked for",
  "object storage": "flat storage of immutable blobs behind an HTTP API (S3, GCS); cheap, durable, high-latency per request",
  S3: "Amazon's object storage; the reference for 'blob store' throughout",
  GCS: "Google Cloud Storage, an object store like S3",
  ETag: "an HTTP header carrying a version tag for a resource; used for conditional requests and multipart integrity",
  "multipart upload": "uploading a large object as independent parts, then committing them as one in a final call",
  "presigned URL": "a URL carrying a signature that lets the holder read or write one object directly for a short time",
  "pre-signed PUT": "a URL a client can upload directly to, so bytes never pass through the application servers",
  Redis: "an in-memory data store with rich data types (sorted sets, hashes) and single-threaded atomic commands",
  "sorted set": "a Redis structure keeping members ordered by a score; rank and range queries are logarithmic",
  ZSET: "a Redis sorted set: members ordered by score, rank lookups in logarithmic time",
  ZADD: "Redis: add a member to a sorted set with a score",
  ZREVRANK: "Redis: a member's position counting from the highest score",
  ZREVRANGE: "Redis: the members in a rank range, highest score first",
  ZREM: "Redis: remove a member from a sorted set",
  "skip list": "a layered linked list where each level skips over more items; logarithmic search and ordered iteration",
  "Lua script": "a script Redis runs atomically on one shard, so read-modify-write cannot interleave with other commands",
  TTL: "time to live: how long an entry stays before it expires on its own",
  LRU: "least recently used: evict the entry that has gone longest without being read",
  "W-TinyLFU": "an admission policy that only lets a new key into the cache if it is seen more often than the key it would evict",
  "S3-FIFO": "a cache eviction policy using three queues that discards one-hit items quickly; simpler than LRU and often better",
  Postgres: "the reference relational database throughout: transactions, row locks, write-ahead log",
  "FOR UPDATE": "SQL: lock the selected rows until the transaction ends so no one else can change them",
  "SKIP LOCKED": "SQL: skip rows another transaction has locked instead of waiting, so workers can share a queue table",
  "ON CONFLICT DO NOTHING": "SQL: an insert that quietly becomes a no-op when a unique key already exists",
  OLAP: "analytical queries over many rows and few columns; the opposite workload from a transaction store",
  OLTP: "many small transactional reads and writes; the workload a relational database is built for",
  "materialised view": "a query result stored as a table and refreshed, so reads do not recompute it",
  // --- messaging ---
  Kafka: "a partitioned, replicated, append-only log; consumers read at their own offset and the log is retained by time, not by consumption",
  partition: "one ordered shard of a topic; ordering is guaranteed only within a partition",
  "partition key": "the field hashed to choose a partition; everything with the same key lands in order on one partition",
  offset: "a consumer's position in a partition; committing it is how progress is recorded",
  "consumer group": "a set of consumers that split a topic's partitions between them, each partition read by exactly one member",
  ISR: "in-sync replicas: the partition replicas currently caught up with the leader; only they may become leader",
  "acks=all": "a Kafka producer setting: the write is acknowledged only when every in-sync replica has it",
  "high watermark": "the offset up to which every in-sync replica has the data; consumers cannot read past it",
  KRaft: "Kafka's built-in Raft-based controller quorum, replacing the ZooKeeper dependency",
  "compacted topic": "a Kafka topic that keeps only the latest value per key instead of a time window",
  DLQ: "dead-letter queue: where a message goes after its retries are exhausted, so it stops blocking and can be inspected",
  "dead letter": "a message moved aside after repeated failure so it neither blocks the queue nor is lost",
  backpressure: "a downstream component signalling upstream to slow down instead of buffering without bound",
  "fan-out": "one event delivered to many recipients; the cost grows with the recipient count",
  "fan-in": "many sources read and merged into one result at read time",
  "pub/sub": "publish-subscribe: producers publish to a topic and every subscriber receives each message",
  SQS: "Amazon's hosted work queue; at-least-once, no ordering by default",
  RabbitMQ: "a broker that routes messages to queues and deletes them once consumed; a mailbox, not a log",
  "NATS JetStream": "a lightweight streaming broker with persistence and consumer groups",
  "ring buffer": "a fixed-size circular array where the producer overwrites the oldest slot; no allocation, bounded memory",
  Disruptor: "the LMAX ring-buffer pattern for passing events between threads without locks or allocation",
  conflation: "collapsing several updates to the same key into the latest one when a consumer cannot keep up",
  "head-of-line blocking": "one slow item at the front of a queue delays everything behind it",
  // --- networking, edge, delivery ---
  CDN: "content delivery network: caches at edge locations near users so most requests never reach your origin",
  PoP: "point of presence: one edge site of a CDN or service",
  POP: "point of presence: one edge site of a CDN or service",
  anycast: "one IP address announced from many sites; the network routes each user to the nearest",
  BGP: "the routing protocol between networks on the internet; anycast works by announcing the same prefix from many places",
  ASN: "autonomous system number: the id of one network on the internet, such as an ISP",
  ISP: "internet service provider, the network a user's device is attached to",
  IXP: "internet exchange point: a facility where networks connect directly instead of paying a transit provider",
  "origin shield": "a single cache tier between many edges and the origin so a miss reaches the origin once",
  "single-flight": "when many identical requests arrive at once, do the work once and hand every caller the same result",
  "thundering herd": "many clients retrying or refilling at the same instant and overwhelming the thing they depend on",
  "stale-while-revalidate": "serve the cached copy immediately and refresh it in the background",
  SWR: "stale-while-revalidate: serve the cached copy now, refresh it in the background",
  "Cache-Control": "the HTTP header that tells caches how long and whether they may keep a response",
  "max-age": "the Cache-Control directive giving the number of seconds a response may be cached",
  "301": "HTTP moved permanently: browsers cache it and never ask again",
  "302": "HTTP found (temporary redirect): browsers ask again next time, so the redirect can be counted and changed",
  "304": "HTTP not modified: the cached copy is still valid, no body is sent",
  "404": "HTTP not found",
  "409": "HTTP conflict: the request contradicts the current state, typically a lost compare-and-set",
  "410": "HTTP gone: the resource existed and has been deliberately removed",
  "429": "HTTP too many requests: the caller is rate-limited and should back off",
  "Retry-After": "the HTTP header telling a rate-limited or busy client how long to wait",
  "503": "HTTP service unavailable",
  WebSocket: "a long-lived two-way connection over one TCP socket, so the server can push without the client polling",
  SSE: "server-sent events: a one-way stream of events from server to browser over a plain HTTP response",
  "long polling": "the client asks and the server holds the request open until it has something to send",
  gRPC: "a binary RPC framework over HTTP/2 with generated client and server code",
  Protobuf: "protocol buffers: a compact binary serialisation format with a schema",
  "HTTP/2": "one connection carrying many multiplexed requests; the basis of gRPC and of push-notification APIs",
  TLS: "the encryption layer under HTTPS; the handshake costs a round trip and CPU unless a session is resumed",
  mTLS: "mutual TLS: both sides present certificates, so services authenticate each other",
  NAT: "network address translation: many devices sharing one public IP, so IP is a poor identity",
  CGNAT: "carrier-grade NAT: an ISP putting thousands of customers behind one public IP",
  DDoS: "a distributed denial-of-service attack: flooding a service from many sources",
  NIC: "network interface card; its line rate bounds how many bytes a host can move",
  "25 GbE": "a 25 gigabit-per-second network interface, roughly 3 GB/s",
  "10 GbE": "a 10 gigabit-per-second network interface, roughly 1.2 GB/s",
  RDMA: "remote direct memory access: one machine writes into another's memory without the CPU or kernel in the path",
  "kernel bypass": "networking that skips the operating system's stack to shave microseconds",
  multicast: "one packet delivered to every subscriber on the network segment at once",
  "reliable multicast": "multicast plus sequence numbers and a gap-fill channel so receivers can detect and repair loss",
  "L4 load balancer": "a balancer that spreads TCP connections without looking inside them",
  "L7": "the application layer: a load balancer or proxy that understands HTTP requests",
  GeoDNS: "answering a DNS query with an address near the client's location",
  DNS: "the lookup from a host name to an IP address; cached with a TTL",
  // --- rate limiting, admission ---
  GCRA: "generic cell rate algorithm: a token bucket stored as a single timestamp, so the check is one compare and one write",
  TAT: "theoretical arrival time: the single timestamp GCRA stores per key, the moment the next request would be allowed at the steady rate",
  "X-RateLimit": "the response headers (limit, remaining, reset) that tell a well-behaved client how much budget it has left",
  "shadow mode": "running a new rule and recording what it would have decided, without enforcing it",
  "token bucket": "a bucket refilled at a fixed rate; each request takes a token and is refused when the bucket is empty",
  "sliding window": "counting requests in the last N seconds precisely, or approximating it from two fixed windows",
  "circuit breaker": "after repeated failures stop calling the dependency for a while, then probe; turns a slow failure into a fast one",
  "fail open": "when the check cannot be made, allow the request",
  "fail closed": "when the check cannot be made, refuse the request",
  jitter: "a random delay added to retries so a crowd of clients does not retry in lockstep",
  "exponential backoff": "retry after 1, 2, 4, 8... units, so a struggling service is not hammered",
  bulkhead: "isolating resources per tenant or feature so one exhausting them cannot take the rest down",
  "admission control": "deciding at the door how much work to accept based on capacity, not per-client quotas",
  // --- scale words ---
  QPS: "queries per second",
  "req/s": "requests per second",
  DAU: "daily active users",
  MAU: "monthly active users",
  p50: "the median latency: half of requests are faster",
  p99: "the latency that 99% of requests beat; the tail that users notice",
  SLO: "service level objective: the latency or availability target the design is held to",
  SLA: "service level agreement: an SLO with consequences attached",
  RPO: "recovery point objective: how much recent data may be lost in a failure",
  RTO: "recovery time objective: how long the system may be down in a failure",
  AZ: "availability zone: one data-centre failure domain within a region",
  DR: "disaster recovery: surviving the loss of a whole region or site",
  MTBF: "mean time between failures",
  AFR: "annualised failure rate, typically of a disk",
  Zipf: "a skewed distribution where the k-th most popular item is roughly 1/k as popular as the first; how real traffic looks",
  Zipfian: "following a Zipf distribution: a few items carry most of the traffic",
  goodput: "the throughput of useful work, after retries, duplicates and failures are discounted",
  "hot key": "one key receiving far more traffic than its share, overloading whichever shard holds it",
  hotspot: "one shard or key taking far more load than the others",
  "blast radius": "how much of the system one failure or bad deploy takes with it",
  "cold start": "the delay while a fresh instance or empty cache warms up",
  // --- sharding, hashing ---
  "consistent hashing": "placing keys and nodes on a ring so adding a node moves only the keys next to it, not 1/N of everything",
  vnode: "virtual node: one of many ring positions a physical node owns, so load spreads evenly",
  "rendezvous hashing": "each key scores every node and picks the highest; adding a node moves only the keys it wins",
  shard: "one horizontal slice of a data set, owned by one node or group",
  "shard key": "the field that decides which shard a row lives on",
  rebalance: "moving shards between nodes as capacity or membership changes",
  xxHash: "a very fast non-cryptographic hash, used where speed matters and adversarial input does not",
  "SHA-256": "a cryptographic hash; 32 bytes, collision-resistant, used for content addressing and integrity",
  MD5: "an old fast hash, broken for security but still used for checksums such as S3 ETags",
  CRC32C: "a fast checksum that detects corruption, not tampering",
  HMAC: "a hash keyed with a secret, so a signature can be verified only by holders of the key",
  Snowflake: "Twitter's 64-bit id scheme: a timestamp, a machine id and a sequence, sortable by time with no coordination",
  UUIDv7: "a UUID whose leading bits are a timestamp, so ids sort by time and index well",
  base62: "encoding a number with the 62 characters a-z, A-Z, 0-9; 7 characters cover 3.5 trillion values",
  // --- search, ranking, ML ---
  "inverted index": "for every term, the list of documents containing it; the structure behind text search",
  postings: "the list of documents (and positions) for one term in an inverted index",
  BM25: "the standard keyword ranking formula: term frequency, document length and rarity of the term",
  "block-max WAND": "a query evaluation trick that skips blocks of postings whose best possible score cannot reach the current top-k",
  FST: "finite state transducer: a compact automaton mapping strings to values, used for dictionaries and autocomplete",
  trie: "a tree keyed one character per level; every prefix is a path",
  "top-K": "the K highest-scoring items",
  "k-way merge": "merging K sorted lists into one sorted stream by repeatedly taking the smallest head",
  "cross-encoder": "a model that scores a query and a document together; accurate and too slow for more than a few hundred candidates",
  "two-tower": "a model with separate query and item encoders whose vectors are compared by dot product, so items can be pre-computed",
  embedding: "a vector of numbers representing an item so that similar items are near each other",
  ANN: "approximate nearest neighbour search: finding vectors close to a query without comparing against every vector",
  HNSW: "a graph index for approximate nearest neighbour search; fast and accurate, but the whole index lives in RAM",
  "IVF-PQ": "an ANN index that clusters vectors (IVF) and compresses each to a few bytes (product quantisation); fits billions in RAM",
  "product quantisation": "compressing a vector by encoding each chunk as the id of its nearest centroid",
  GBDT: "gradient-boosted decision trees: a fast, accurate ranking model for tabular features",
  RRF: "reciprocal rank fusion: merge several rankings by summing 1/(60 + rank) for each item",
  recall: "the fraction of the relevant items a retrieval step actually returns",
  nDCG: "a ranking quality metric that rewards relevant items near the top",
  RAG: "retrieval-augmented generation: fetch relevant text first, then have the language model answer from it",
  "KV cache": "in a language model, the attention keys and values kept for every generated token so they are not recomputed",
  prefill: "processing the whole prompt in one pass to fill the KV cache; compute-bound",
  decode: "generating one token per step from the KV cache; memory-bandwidth-bound",
  TTFT: "time to first token: the prompt-processing latency a user sees before output starts",
  ITL: "inter-token latency: the delay between successive generated tokens",
  MFU: "model FLOPs utilisation: the fraction of a GPU's peak arithmetic rate the model actually uses",
  "TP=8": "tensor parallelism across 8 GPUs: each layer's matrices are split across all eight, joined by fast interconnect",
  NVLink: "NVIDIA's high-bandwidth link between GPUs in one server",
  HBM: "high-bandwidth memory: the GPU's on-package RAM; capacity and bandwidth bound what a model can serve",
  "Count-Min sketch": "a small fixed-size array of counters that estimates any key's count, only ever over-counting",
  HLL: "HyperLogLog: a few kilobytes that estimate the number of distinct items to within a couple of percent",
  EWMA: "exponentially weighted moving average: a running average that forgets the past geometrically",
  "z-score": "how many standard deviations a value is from its baseline",
  MinHash: "a hashing trick that estimates how similar two sets are from a few hash values",
  SimHash: "a fingerprint where similar documents get fingerprints that differ in few bits",
  "Hamming distance": "the number of bit positions in which two fingerprints differ",
  Flink: "a stream processor with checkpointed state, event-time windows and exactly-once output",
  Spark: "a batch (and micro-batch) processing engine for large data sets",
  watermark: "in stream processing, a timestamp asserting that no event older than it will arrive",
  "tumbling window": "fixed, non-overlapping time buckets, such as every 60 seconds",
  checkpoint: "a consistent snapshot of a stream job's state from which it can restart without loss",
  // --- media ---
  ABR: "adaptive bitrate: the player picks a quality rung per segment from what the network is delivering",
  HLS: "HTTP live streaming: video cut into small files listed in a manifest, fetched over plain HTTP",
  DASH: "the standard equivalent of HLS: segmented video over HTTP with a manifest",
  CMAF: "a common segment format that both HLS and DASH can reference, so video is encoded and stored once",
  fMP4: "fragmented MP4: the segment container CMAF uses",
  manifest: "the file listing a stream's rungs and segments; the player reads it before fetching video",
  rung: "one quality level (resolution and bitrate) in an encoding ladder",
  "encoding ladder": "the set of quality rungs a video is encoded at, so players can pick one per network",
  GOP: "group of pictures: a keyframe and the frames that depend on it; a decoder can only start at a keyframe",
  keyframe: "a video frame encoded on its own, without reference to earlier frames; the only place playback can start",
  transcode: "decoding a video and re-encoding it at other resolutions, bitrates or codecs",
  AV1: "a modern open video codec; smaller files than H.264 at much higher encoding cost",
  "H.264": "the most widely supported video codec; every device decodes it",
  DRM: "digital rights management: encrypting media so only licensed players can decrypt it",
  CENC: "common encryption: encrypt a video once so Widevine, PlayReady and FairPlay can all decrypt it with their own licences",
  Widevine: "Google's DRM system, used by Chrome and Android",
  SFU: "selective forwarding unit: a relay that forwards each participant's stream to the others without decoding it",
  MCU: "multipoint control unit: a server that decodes every stream and mixes them into one; expensive, used for large calls",
  RTP: "the real-time transport protocol carrying audio and video packets with timestamps and sequence numbers",
  WebRTC: "the browser stack for real-time audio and video: RTP, congestion control and NAT traversal",
  simulcast: "a sender uploads several quality layers at once so the relay can forward a cheaper one to slow receivers",
  SVC: "scalable video coding: one stream with layers that can be dropped to lower quality without re-encoding",
  "jitter buffer": "a small receiver-side buffer that smooths packet arrival variation at the cost of delay",
  FEC: "forward error correction: sending redundant packets so a lost one can be rebuilt without a retransmit",
  NACK: "a receiver asking the sender to retransmit a specific lost packet",
  PLI: "picture loss indication: a receiver asking the sender for a fresh keyframe",
  TWCC: "transport-wide congestion control: receiver feedback on packet arrival the sender uses to estimate bandwidth",
  Opus: "the standard low-latency audio codec used in real-time calls",
  STUN: "a way for a device behind NAT to learn its public address so peers can reach it",
  TURN: "a relay used when two devices cannot connect directly through their NATs",
  Vorbis: "an open audio codec",
  // --- geo ---
  geohash: "encoding a latitude/longitude into a string where a shared prefix means nearby",
  S2: "Google's scheme dividing the sphere into hierarchical cells along a space-filling curve",
  H3: "Uber's hexagonal hierarchical geo-cell scheme",
  haversine: "the formula for the great-circle distance between two points on a sphere",
  "map matching": "snapping noisy GPS points to the road or segment they most likely came from",
  "contraction hierarchies": "preprocessing a road graph with shortcuts so a shortest-path query touches a tiny fraction of it",
  CCH: "customisable contraction hierarchies: the shortcut structure is fixed and edge weights can be swapped in seconds",
  Dijkstra: "the basic shortest-path algorithm: expand the nearest unvisited node until the target is reached",
  "A*": "Dijkstra guided by a lower-bound estimate of the remaining distance, so it expands fewer nodes",
  DEM: "digital elevation model: a raster of ground heights, sampled to compute elevation gain",
  "Douglas-Peucker": "an algorithm that drops the points of a polyline that change its shape the least",
  isochrone: "the region reachable within a given travel time",
  // --- security, auth ---
  OAuth: "a protocol for delegating access: a user lets one service act on their behalf at another without sharing a password",
  OIDC: "OpenID Connect: OAuth plus a signed identity token that says who logged in",
  JWT: "JSON web token: a signed set of claims a service can verify locally without calling the issuer",
  JWKS: "the published set of public keys used to verify an issuer's tokens",
  PKCE: "proof key for code exchange: binds an OAuth code to the client that requested it so a stolen code is useless",
  TOTP: "time-based one-time password: the six-digit code an authenticator app shows",
  WebAuthn: "passkeys and security keys: a challenge signed by a device-held private key, resistant to phishing",
  argon2id: "a memory-hard password hash designed to be slow on GPUs",
  bcrypt: "an older adaptive password hash",
  KMS: "key management service: a cloud service that holds encryption keys and performs operations without releasing them",
  HSM: "hardware security module: a tamper-resistant device that holds keys",
  RBAC: "role-based access control: permissions attached to roles, roles to users",
  ACL: "access control list: who may do what to a specific object",
  Zanzibar: "Google's relationship-based authorisation system: permissions as tuples like doc:42#viewer@user:alice",
  "credential stuffing": "trying leaked username/password pairs from one site on another",
  XSS: "cross-site scripting: injected script running in another user's browser",
  CSRF: "cross-site request forgery: a hostile page making the browser send an authenticated request",
  SPF: "an email DNS record listing which servers may send for a domain",
  DKIM: "a signature in an email's headers that the sending domain's DNS key verifies",
  DMARC: "a domain's policy for mail that fails SPF and DKIM: none, quarantine or reject",
  SMTP: "the protocol for delivering email between servers; the only irreversible step is the reply to DATA",
  IMAP: "the protocol a mail client uses to read a mailbox on a server",
  MX: "the DNS record naming the servers that receive a domain's mail",
  "PCI-DSS": "the card industry's security standard; handling raw card numbers puts you in scope",
  PSP: "payment service provider (Stripe, Adyen): the party that actually charges the card",
  "3DS": "3-D Secure: the bank's extra authentication step during a card payment",
  chargeback: "a cardholder disputing a charge through their bank, months after the fact",
  "double-entry": "every money movement recorded as a debit and a matching credit, so the books always balance",
  ledger: "an append-only record of money movements; balances are derived from it, never edited",
  // --- infra ---
  Kubernetes: "the container orchestrator: schedules pods onto nodes, restarts them, scales them",
  "Firecracker": "a lightweight virtual machine monitor used to give each job its own kernel in milliseconds",
  microVM: "a minimal virtual machine that boots in milliseconds and isolates one job",
  canary: "releasing to a small fraction first and comparing its health against the rest before continuing",
  "blue-green": "two full environments; traffic switches from the old to the new and back if needed",
  "feature flag": "a runtime switch that turns behaviour on or off without a deploy",
  NTP: "network time protocol: how machines keep their clocks within milliseconds of each other",
  PTP: "precision time protocol: hardware-assisted clock sync to microseconds",
  "clock drift": "a machine's clock running fast or slow relative to true time, typically tens of parts per million",
  "leap smear": "spreading a leap second over a day so clocks never step",
  Temporal: "a workflow engine that persists each step of a long-running process so it can resume after a crash",
  "Step Functions": "AWS's hosted workflow engine",
  Envoy: "a proxy used as a gateway or sidecar for routing, retries and observability",
  Terraform: "infrastructure defined in files and applied as a plan",
  FPGA: "a chip whose logic is configured rather than programmed; used for deterministic microsecond processing",
  NUMA: "non-uniform memory access: on a multi-socket machine, memory attached to the other socket is slower",
  "cache line": "the 64-byte unit a CPU moves between memory and its caches; two hot fields in one line contend",
  "false sharing": "two cores writing different fields that share a cache line, each invalidating the other",
  JVM: "the Java virtual machine; its garbage collector can pause a process",
  "GC pause": "a garbage-collection stop during which the process does no work; can exceed a lease timeout",
  OOM: "out of memory: the process exceeds its limit and is killed",
  APNs: "Apple's push notification service",
  FCM: "Firebase Cloud Messaging, Google's push notification service",
  SES: "Amazon's email sending service",
  Twilio: "an SMS and voice API provider",
  Elasticsearch: "a distributed search engine built on Lucene: inverted indexes sharded and replicated across nodes",
  OpenSearch: "the open-source fork of Elasticsearch",
  Lucene: "the Java search library underneath Elasticsearch",
  PromQL: "Prometheus's query language over time series",
  Prometheus: "a pull-based metrics store: scrapes targets, keeps time series, evaluates alert rules",
  TSDB: "time-series database: optimised for appending timestamped samples and querying ranges",
  cardinality: "the number of distinct series or keys; the thing that actually sizes a metrics system",
  Gorilla: "Facebook's time-series compression: delta-of-delta timestamps and XOR-ed values, about 1.4 bytes per sample",
  FIX: "the text protocol banks and venues use for orders",
  ITCH: "Nasdaq's binary market-data feed protocol",
  "order book": "the two sorted lists of resting buy and sell orders at each price for one instrument",
  "price-time priority": "orders at a better price fill first; at the same price, the earliest fills first",
  tick: "the smallest price increment an instrument trades in",
  FIFO: "first in, first out",
  IOC: "immediate-or-cancel: fill what you can now and cancel the rest",
  FOK: "fill-or-kill: fill the whole order now or cancel all of it",
  STP: "self-trade prevention: stopping a firm's own orders from matching against each other",
  KOM: "king of the mountain: Strava's title for the fastest time on a segment",
  ADR: "average daily rate: the mean price a hotel room sells for",
  ISBN: "the standard identifier printed on a book edition",
  ISRC: "the standard identifier for one recording of a track",
  ETA: "estimated time of arrival",
  WARC: "the standard archive format for crawled web pages, keeping headers with bodies",
  "robots.txt": "the file a site publishes to say which paths crawlers may fetch and how fast",
  "spider trap": "a site that generates endless distinct URLs, so a crawler never finishes it",
  ULID: "a 128-bit id whose first 48 bits are a timestamp, so it sorts by time",
  CRDT: "a data type whose concurrent updates merge automatically without conflicts",
  OT: "operational transformation: rewriting a concurrent edit against the edits it did not see so both can apply",
  SPA: "single-page application: a web app whose pages are rendered by script in the browser",
  ORM: "object-relational mapper",
  CI: "continuous integration: building and testing every change automatically",
  DAG: "directed acyclic graph: a set of steps with dependencies and no cycles",
  SHA: "a git commit or content hash",
  RTT: "round-trip time: the time for a request to reach the other side and a reply to come back",
  "cache-aside": "the application reads the cache, falls back to the store on a miss, and fills the cache itself",
  "write-through": "writes go to the cache and the store together",
  "write-behind": "writes go to the cache and are flushed to the store later",
  "in-process": "inside the same operating-system process, so a call is a function call, not a network hop",
  "hot path": "the sequence of steps every request takes; the part of the system whose latency users feel",
  "control plane": "the part that configures and coordinates, as opposed to the data plane that serves requests",
  "data plane": "the part that handles the actual requests and bytes",
  "scatter-gather": "sending one query to many shards and merging their answers",
  "read amplification": "how many reads a store does to answer one",
  "write path": "the components a write passes through",
  "read path": "the components a read passes through",
  "cursor": "an opaque position token for paging through results without offsets",
  "high-water mark": "the highest position a consumer has fully processed",
  "graceful degradation": "losing a feature or precision under stress instead of failing entirely",
  "bounded staleness": "data that may be old, but never older than a stated limit",
};

/** Case-insensitive lookup for word terms; acronyms are matched as written. */
export function define(term: string): string | undefined {
  return GLOSSARY[term] ?? GLOSSARY[term.toLowerCase()];
}
