import type { Diagram } from "./types";

export const MARKET_DATA_INGEST: Diagram = {
  id: "market-data-ingest",
  title: "Market Data Ingest",
  question: "Design a High-Throughput Market Data Ingest Pipeline",
  sourceId: "patterns",
  itemId: 43,
  overview: {
    shape:
      "Fan in, sequence, fan out, plus one rule about what you are allowed to drop: many venue feeds converge on a single writer that stamps one total order, and that order is then split by instrument and handed to the per-instrument matching cores that execute trades.",
    beats: [
      {
        text: "The edge is deliberately stupid. One thin handler per inbound stream does nothing but drain the socket and decode the venue's frame, because the moment a reader blocks on downstream work the kernel receive buffer fills, and on UDP multicast that is silent packet loss at the worst possible place.",
        lights: ["edge-group", "feed-handlers", "e1"],
      },
      {
        text: "Normalisation is where three protocols become one. FIX, an ITCH-style binary and a proprietary frame all decode into the same fixed canonical event, into pre-allocated structs rather than fresh objects, because a per-message allocation at 2M msg/s is a garbage collection pause and a pause blows a microsecond budget.",
        lights: ["normaliser", "e6", "e8"],
      },
      {
        text: "The sequencer is the whole correctness claim. A single writer assigns the next monotonic number and writes a pre-allocated slot, which gives one gap-free total order across every instrument without a lock, plus a journal that is the source of truth for replay. One writer is the mechanism, not a compromise.",
        lights: ["sequencer", "ordered-ring", "journal", "e9", "e10"],
      },
      {
        text: "Fan out is partitioning, never load balancing. Dispatch by hash(instrumentId) so a book always lands on the same consumer in sequence order; round-robin would interleave one book across shards and destroy the only ordering guarantee that downstream matching depends on.",
        lights: ["dispatch", "shards", "e14"],
      },
      {
        text: "Overload is decided per message class, not per system. Ticks are snapshots you overwrite, so a lagging shard gets conflation, the latest tick per instrument replacing the stale one. Order flow accumulates and can never be silently dropped, so it gets backpressure or an explicit busy reject, and every buffer between stages is bounded so overload has a defined outcome instead of an out-of-memory.",
        lights: ["conflation", "order-gateway", "e12", "e15"],
      },
      {
        text: "What actually gets drilled is the hole in the feed. The venue's own per-feed sequence is the only thing that makes loss visible, and the recovery ladder runs fastest first: the redundant B copy in tens of microseconds, a retransmit request at 5 to 50 ms, then a snapshot refresh for anything unbounded, with the affected instruments marked stale and unpublishable while the gap is open.",
        lights: ["gap-arb", "venue-feeds", "e2", "e3", "e4"],
      },
    ],
    crux:
      "You have to classify traffic before you size any buffer. Under overload the question is not how deep the queue is, it is which messages are state you overwrite and which are state you accumulate. Get that split wrong and the pipeline either loses trades or dies of memory exhaustion, and no amount of tuning rescues either.",
    numbers: [
      "2M msg/s planning peak across ~10k instruments",
      "~32B packed binary: 64 MB/s, versus 300-500 MB/s as JSON",
      "B copy fills a gap in tens of µs; retransmit costs 5-50 ms",
    ],
  },
  nodes: [
    {
      id: "edge-group",
      kind: "zone",
      label: "Ingest edge (must never block)",
      detail: {
        what: "The per-stream handlers plus the gap and arbitration logic that watches the venue's own sequence numbers on every feed.",
        why: "It is one zone because everything inside it is bound by a single rule: no work here may ever stall the socket drain. Business logic, gap repair and staleness decisions all run off the drain path, so the kernel buffer stays empty even when the rest of the pipeline is saturated.",
        numbers: ["one handler per inbound stream, pinned to a core", "reorder buffer 1024 slots x 64B = 64KB per feed"],
        breaks:
          "Any blocking call that creeps into a handler, a lock, a log format, a metrics allocation, turns backpressure into dropped multicast packets that nothing upstream will ever tell you about.",
      },
    },
    {
      id: "venue-feeds",
      label: "Venue feeds",
      sub: "FIX, ITCH binary, proprietary",
      kind: "external",
      col: 0,
      row: 0,
      detail: {
        what: "The venues themselves, each publishing a tick firehose as two identical multicast copies on separate network paths, plus a per-feed monotonic sequence number on every message. Each venue also runs its own repair endpoints: a retransmit request-response service for a missing sequence range, and a periodic full-state snapshot channel.",
        why: "Drawn explicitly because it sets every constraint downstream answers to: a different wire protocol per venue, an arrival rate you do not control, and a transport that will never tell you it lost a packet. The repair endpoints belong to somebody else too, which is why both are rate limited and capped.",
        numbers: [
          "2M msg/s planning peak at open, close and on news",
          "top 10 symbols carry 30-40% of all traffic",
          "~24-40B per packed canonical tick",
          "retransmit round trip 5-50 ms; snapshot interval 1-30 s",
        ],
        breaks:
          "The venue's sequence number is arrival order at our NIC, not the order the markets actually moved, so two venues quoting the same instrument are ranked by path length and nothing in this pipeline can fix that. A venue-wide burst also means every participant hits the recovery service at once, exactly when it is slowest.",
      },
    },
    {
      id: "order-gateway",
      label: "Order entry gateway",
      sub: "per-participant credit quotas",
      kind: "service",
      col: 1,
      row: 0,
      detail: {
        what: "The control-plane path for order flow: submit_order and cancel_order arrive here, are counted against a per-participant quota, and either enter the pipeline or are rejected explicitly.",
        why: "Order flow is the traffic class that may never be silently dropped, so its admission has to be rationed somewhere. Every request is answered accepted, rejected or told busy, and counting at the edge means one participant's cancel-and-replace storm is rejected before it consumes shard capacity, rather than after it has already filled a ring the market data path shares.",
        numbers: ["orderflow.nack_rate should sit at zero"],
        breaks:
          "Sustained order-flow overload has no graceful answer. Backpressure penalises everyone on that producer connection and a reject is a visible failure to a paying client; buffering only relocates the failure and makes it bigger.",
        choice: {
          pick: "Per-participant message credits at the gateway, with a documented busy reject code",
          instead: "One shared bounded queue in front of the shards, buffering whoever arrives.",
          decider: "Blast radius under a single participant's burst. A shared queue at 2^20 slots absorbs about 0.5s of a 2M msg/s burst and then rejects everybody, including the quiet participants; per-participant credits reject only the one client whose burst caused it, and keep the gateway thin because it counts rather than parses.",
          flips: "A venue with a handful of trusted internal producers, where quota accounting costs more than it saves and a single bounded queue is honest enough.",
        },
      },
    },
    {
      id: "feed-handlers",
      label: "Feed handlers",
      sub: "one per stream, drain only",
      kind: "service",
      col: 0,
      row: 1,
      parent: "edge-group",
      detail: {
        what: "One thin process or thread per inbound stream whose entire job is to pull packets off the socket as fast as they arrive and hand them to a bounded per-stream ring.",
        why: "The reader must never block on downstream work. On TCP a slow reader becomes backpressure onto the sender; on UDP multicast the kernel receive buffer fills and packets are dropped with no error anywhere, which corrupts the feed view at exactly the moment the market is busiest. Handlers are pinned to cores and busy-poll rather than block on the socket.",
        numbers: ["~50-80 MB/s binary ingress at 2M msg/s"],
        breaks:
          "A handler process dying takes one feed dark, and the symptom is a message rate that falls to zero rather than an error; the per-feed heartbeat is what catches it, and gap detection replays the missed range on restart.",
        choice: {
          pick: "Binary UDP multicast for the tick firehose, kept separate from the control plane",
          instead: "gRPC server-streaming over HTTP/2 for both the firehose and the service feeds.",
          decider: "Egress multiplication and tail latency. One multicast publish at 2M msg/s and 32 bytes is 64 MB/s no matter how many consumers subscribe; unicast to 20 consumers is 1280 MB/s, past 10 GbE line rate. TCP also head-of-line blocks, so one lost segment stalls everything behind it for a retransmit round trip of 100-200 µs against a p99 budget of tens of µs.",
          flips: "Consumers in the single digits, or any cloud deployment, since multicast is not natively available inside most VPCs. If the budget is milliseconds the head-of-line cost vanishes into the noise and the reliable stream deletes this whole gap subsystem.",
        },
      },
    },
    {
      id: "gap-arb",
      label: "Arbitration + gap detect",
      sub: "dual-feed dedup, expected counter",
      kind: "service",
      col: 0,
      row: 2,
      parent: "edge-group",
      detail: {
        what: "Per feed, an expected counter over the venue's sequence plus a small reorder buffer: keep whichever of the A or B copies lands first, discard the duplicate, and start a timer when a message arrives above expected.",
        why: "Multicast will never report a loss, so the venue's own per-feed number is the only evidence a packet went missing. A gap is often just reordering, which is why the timer exists at all rather than firing a retransmit on the first out-of-order message.",
        numbers: ["reorder buffer 1024 slots x 64B = 64KB per feed", "gap timer 5-10 ms colocated", "B copy typically arrives within tens of µs, well under the 5-50ms retransmit"],
        breaks:
          "Too aggressive a timer floods the venue's recovery service at precisely the moment every other participant is doing the same; too slow a timer and the instrument sits stale and unpublishable for longer than it needed to.",
        choice: {
          pick: "Subscribe to both redundant multicast copies and arbitrate, with retransmit as the second line",
          instead: "Subscribe to one copy, detect gaps, and request a retransmit whenever one appears.",
          decider: "Recovery latency against hardware cost. Arbitration hides any loss confined to one path within the arrival spread between copies, tens of µs, with no round trip at all; a retransmit costs 5-50 ms during which the instrument is unpublishable. The price is 2x ingress, another 64 MB/s and roughly one more core per feed.",
          flips: "When the second path is not genuinely independent, same switch or same AZ, so arbitration buys nothing. At one gap per hour with 20 ms recovery that is 0.0006% stale time, which nobody funds a second NIC to remove.",
        },
      },
    },
    {
      id: "normaliser",
      label: "Normaliser",
      sub: "decode into pooled structs",
      kind: "service",
      col: 1,
      row: 1,
      detail: {
        what: "Per-venue decoders that turn every wire format into one fixed canonical event: seq, instrument_id, kind, venue, side, price, quantity, source_ts, ingest_ts.",
        why: "Three protocols cannot each be understood by the sequencer and the shards, so the variability is absorbed once, here. Carrying both timestamps is deliberate: source_ts is the venue's clock, ingest_ts is ours, and consumers reasoning about cross-venue causality need both.",
        numbers: ["~24-40B packed per canonical event", "zero steady-state allocation on the hot path"],
        breaks:
          "A fresh object per message is a garbage collection pause, and a pause of even a few milliseconds is hundreds of thousands of queued messages at 2M msg/s.",
        choice: {
          pick: "Allocation-free decode into pooled fixed-size structs, packed binary",
          instead: "JSON or a self-describing format decoded into fresh objects per message.",
          decider: "Bytes and pause time. The same tick is ~32B packed and 150-250B as JSON, so 64 MB/s becomes 300-500 MB/s, a 6-10x bandwidth and parse-cost penalty, before you count the allocation churn that a per-message object graph creates.",
          flips: "The control plane, where the rate is low and human-legible payloads with real tooling are worth far more than the bytes they cost.",
        },
      },
    },
    {
      id: "sequencer",
      label: "Sequencer",
      sub: "single writer, assign seq",
      kind: "service",
      col: 1,
      row: 2,
      detail: {
        what: "One thread that does exactly three things per event: increment the sequence, write it into a claimed ring slot, and append it to the journal.",
        why: "This is the point where many streams become one ordered stream, and one writer is what makes that order deterministic without a lock or a CAS. It also has to do nothing else: no parsing, no risk checks, no formatted logging, because every microsecond spent here comes straight off the venue's throughput ceiling.",
        numbers: ["LMAX published 6M+ msg/s on 2011 commodity hardware", "~3x headroom against a 2M msg/s peak"],
        breaks:
          "It is a single-writer ceiling by construction, so a saturated sequencer has no incremental fix; at 80% of one core doing only those three things, the only move left is sharding the whole pipeline by instrument range.",
        choice: {
          pick: "One global sequencer per pipeline, giving a total order across every instrument",
          instead: "Sequence independently inside each instrument shard and never claim a global order.",
          decider: "Measured headroom against the actual peak. A stage that only assigns a number and writes a pre-allocated slot sustains millions of ops per second on one core against a 2M msg/s planning peak, about 3x headroom, so the global order is effectively free. Below roughly 2x, stop relying on it.",
          flips: "Peak above half the single-writer ceiling, a deployment already spanning machines so no one writer sees every event, or audit rules requiring each shard to be independently recoverable. The cost is losing the answer to 'what did the venue look like at sequence N', which is the first thing a basket order asks.",
        },
      },
    },
    {
      id: "ordered-ring",
      label: "Ordered ring",
      sub: "2^20 slots, pre-allocated",
      kind: "queue",
      col: 1,
      row: 3,
      detail: {
        what: "The single totally ordered event log as a power-of-two ring buffer with a producer cursor and per-consumer cursors, every slot pre-allocated at startup.",
        why: "It decouples the socket drain from the shards without letting that decoupling become unbounded. Consumers batch-drain everything available in one go, which amortises per-message cost and is a large part of how this shape reaches millions of messages a second on modest hardware.",
        numbers: ["2^20 slots x 64B = 64 MB per ring", "absorbs ~0.5s of a 2M msg/s burst", "warn at 50% depth, ~250 ms of headroom"],
        breaks:
          "It is bounded on purpose, so a sustained overload reaches capacity and the conflation-or-backpressure rule has to be correct; make it unbounded and the failure simply moves from a defined drop to an out-of-memory.",
        choice: {
          pick: "A single-writer shared-memory ring inside one process",
          instead: "A durable partitioned log such as Kafka in the middle of the pipeline.",
          decider: "The latency floor. Ring hand-off is sub-microsecond with no copy, no syscall and no allocation, against a p99 budget of tens of µs; a network hop plus a disk commit per message puts the floor in milliseconds, which is three orders of magnitude past budget.",
          flips: "When consumers are many, heterogeneous and owned by other teams, or when the latency budget is seconds. Then the durable log's replay, independent offsets and free consumer onboarding are worth far more than the microseconds.",
        },
      },
    },
    {
      id: "journal",
      label: "Journal + snapshots",
      sub: "sequential append, snapshot 30s",
      kind: "database",
      col: 2,
      row: 2,
      detail: {
        what: "The sequenced log persisted by sequential append, plus periodic snapshots of consumer state each labelled with the sequence it is current as of.",
        why: "The log, not any in-memory buffer, is the source of truth. Recovery is loading the newest snapshot and replaying forward from its sequence, which is also exactly what a hot standby does continuously, so failover is a promotion rather than a cold rebuild.",
        numbers: ["snapshot every 30s bounds replay to 30s", "RPO zero for anything journalled before ack", "RTO within the ~30s replay bound"],
        breaks:
          "Replay is only useful if it is deterministic, and determinism is a discipline: one wall-clock read, one hash-map iteration or one branch on arrival timing on the processing path and a replay silently stops reproducing the day it is meant to reconstruct.",
        choice: {
          pick: "Memory-mapped sequential append, with snapshots every 30 seconds",
          instead: "A relational database or a replicated broker as the durable record.",
          decider: "Cost per event on the sequencer thread. This is a pure append at up to 2M events/s on the one thread that must not stall; a transactional write per event is orders of magnitude too slow and puts a query planner on the hot path. Snapshot cadence then buys back replay time: 30s cadence, at most 30s to replay.",
          flips: "When other teams need arbitrary historical replay with schemas and offsets, where a real log service is worth the hop that a memory-mapped file will not give you.",
        },
      },
    },
    {
      id: "dispatch",
      label: "Fan-out",
      sub: "hash(instrumentId) % shards",
      kind: "service",
      col: 2,
      row: 3,
      detail: {
        what: "Reads the ordered ring and routes each event to the consumer shard that owns its instrument, preserving the sequence order it was stamped with.",
        why: "Ordering only has to hold within a book and books are independent, so hashing the instrument turns the guarantee into linear parallelism. This is also where the overload decision is taken, per message, by looking at the event kind rather than at the system as a whole.",
        numbers: ["2M / 1e4 = 200 msg/s per instrument on average", "distribution heavily skewed, top 10 take 30-40%"],
        breaks:
          "Skew, not spread. One hot instrument's stream cannot be split without breaking its order, so a whale book is bounded by a single consumer no matter how many shards you add.",
        choice: {
          pick: "Partition by hash(instrumentId), with shards assigned by measured load",
          instead: "Round-robin load balancing across consumers, or least-loaded dispatch.",
          decider: "The ordering guarantee itself. Round-robin interleaves one book across N consumers and destroys per-instrument order, which the deterministic matching core downstream depends on absolutely. Hashing keeps the guarantee and still gives near-linear scale across ~10k instruments; the residual problem is skew, which you solve by assignment, not by spraying.",
          flips: "Stateless edges such as feed-handler gateways or market-data publishers, which carry no per-instrument ordering and should load-balance normally.",
        },
      },
    },
    {
      id: "conflation",
      label: "Conflation map",
      sub: "instrument -> latest tick slot",
      kind: "database",
      col: 2,
      row: 4,
      detail: {
        what: "One slot per instrument holding the latest unconsumed tick, so a new tick for an instrument overwrites the previous queued one instead of joining a queue behind it.",
        why: "A tick is a stateless snapshot, so nobody needs the price from 3 ms ago when a newer one is already waiting. This is the entire mechanism by which the pipeline sheds load without losing anything that matters, and it is why the tick path can be lossy at all.",
        numbers: ["one slot per instrument, ~10k slots"],
        breaks:
          "It owns exactly one rule and must never be widened: an order or cancel placed in this map is a lost trade, because conflation means overwriting state that was meant to accumulate.",
        choice: {
          pick: "A per-instrument latest-value slot for TICK events only",
          instead: "A deeper bounded queue per shard that drops the oldest when full.",
          decider: "Which message you lose when it fills. Dropping the oldest discards the price closest to the current one and keeps stale intermediates; overwriting discards the stale intermediates and keeps the freshest, which is the only tick anyone will act on. Bounded at ~10k slots either way.",
          flips: "Consumers that need every intermediate tick, tape reconstruction or surveillance for example, which must read the journal rather than the conflated live stream.",
        },
      },
    },
    {
      id: "shards",
      label: "Per-instrument shards",
      sub: "one consumer per instrument set",
      kind: "service",
      col: 3,
      row: 3,
      detail: {
        what: "The per-instrument consumers, each draining its own cursor in batches and applying events for its instruments strictly in sequence order.",
        why: "Shared-nothing per book is what makes the pipeline parallel without coordination: no shard needs a lock, and no shard's lag can reorder another's stream. Each also carries the per-instrument stale flag, which has to be visible in what it publishes. Lag is measured as the producer cursor minus the consumer cursor, and the hottest books get dedicated cores with NUMA-local memory.",
        numbers: [],
        breaks:
          "A lagging shard must never propagate back to the socket drain; its ticks conflate and its order flow backpressures at the producer, but the edge keeps draining regardless.",
        choice: {
          pick: "Single-threaded consumer per shard, batch-draining the ring",
          instead: "A thread pool per shard working the same instrument set concurrently.",
          decider: "Determinism against throughput. Concurrent workers on one book reintroduce exactly the ambiguity the single-writer sequencer paid to remove, and no lock scheme restores byte-identical replay. Batching recovers the speed instead: one shard draining in batches carries its share of 2M msg/s comfortably, and an average instrument is only 200 msg/s.",
          flips: "Genuinely commutative per-instrument work such as computing independent analytics, where order does not affect the result and parallelism is free.",
        },
      },
    },
    {
      id: "matching-cores",
      label: "Matching cores",
      sub: "downstream sink, one per shard",
      kind: "external",
      col: 3,
      row: 4,
      detail: {
        what: "The per-instrument matching engines, which take ordered events from this pipeline and turn them into executed trades. This is where the pipeline's responsibility ends.",
        why: "It is the boundary because it is what makes every guarantee upstream non-negotiable. A matching core is a deterministic function of its input, so a reordered or dropped message here is not an estimate that gets corrected later, it is a wrong trade.",
        numbers: ["one core per shard, single threaded"],
        breaks:
          "It has no defence of its own. If this pipeline hands it a book it silently repaired or an event out of order, the core will match against it and produce an execution nobody can undo.",
      },
    },
  ],
  edges: [
    {
      id: "e1",
      from: "venue-feeds",
      to: "feed-handlers",
      tier: "hot",
      label: "A and B multicast copies",
      detail: {
        what: "The tick firehose arriving as two identical multicast streams on separate groups over separate network paths.",
        why: "Two copies exist so that loss confined to one path costs nothing: the handler keeps whichever copy of a given feed sequence lands first. It is the cheapest rung of the recovery ladder because there is no request and no round trip.",
        numbers: ["~50-80 MB/s binary ingress at 2M msg/s", "2x ingress and one extra core per feed"],
        breaks: "If both paths share a switch, a NIC or an AZ, the copies fail together and the redundancy is imaginary while you still pay twice for it.",
      },
    },
    {
      id: "e2",
      from: "feed-handlers",
      to: "gap-arb",
      tier: "control",
      label: "feed_seq per message",
      detail: {
        what: "Every decoded message's venue sequence number handed to the arbitration and gap logic, alongside the main path.",
        why: "Gap detection runs on the venue's sequence space, not ours: theirs can have holes and ours cannot. Keeping this off the drain path is deliberate, because deciding what is missing must never be allowed to slow down reading the socket.",
        numbers: ["one expected counter per feed", "1024-slot reorder buffer"],
        breaks: "A duplicate below expected is dropped, so a venue that resets or wraps its sequence looks exactly like a flood of duplicates and silently stalls the feed.",
      },
    },
    {
      id: "e3",
      from: "gap-arb",
      to: "venue-feeds",
      tier: "control",
      label: "retransmit request",
      detail: {
        what: "A request for a specific missing sequence range, sent once the gap timer expires and the B copy has not filled the hole.",
        why: "The timer exists because most apparent gaps are reordering, and firing on the first out-of-order message means requesting packets that were about to arrive anyway.",
        numbers: ["timer 5-10 ms colocated", "round trip plus queue: 5-50 ms"],
        breaks: "A venue-wide burst makes every participant request at once, so the recovery service is at its slowest exactly when the largest number of people need it.",
      },
    },
    {
      id: "e4",
      from: "venue-feeds",
      to: "gap-arb",
      tier: "control",
      label: "range or snapshot",
      detail: {
        what: "The repair coming back: either the resent messages for the missing range, or a full per-instrument snapshot labelled with the sequence it is current as of.",
        why: "Two different rungs for two different sizes of hole. Retransmit is right for tens of messages; only the snapshot recovers an unbounded gap, and taking it means discarding every buffered incremental at or below its sequence. Venues cap both the resend size and the request rate on this channel.",
        numbers: ["snapshot interval 1-30 s"],
        breaks: "Failing to discard buffered incrementals at or below the snapshot sequence double-applies them, which corrupts the book more quietly than the gap did.",
      },
    },
    {
      id: "e5",
      from: "gap-arb",
      to: "normaliser",
      tier: "data",
      label: "repaired, in feed order",
      detail: {
        what: "Arbitrated and gap-repaired messages rejoining the main path, in the venue's own sequence order.",
        why: "Repair has to complete before the event is stamped with our internal sequence, because our sequence is gap-free by construction and cannot have a hole reserved in it for a message that has not arrived yet.",
        numbers: ["drains up to 1024 buffered slots on each fill"],
        breaks: "A fill that arrives after the pipeline gave up leaves the buffered successors stranded, which is why the reorder buffer is sized for the largest plausible burst behind a hole rather than the average.",
      },
    },
    {
      id: "e6",
      from: "feed-handlers",
      to: "normaliser",
      tier: "hot",
      label: "raw frames, bounded ring",
      detail: {
        what: "Decoded venue frames moving from the drain thread into normalisation over a bounded per-stream ring.",
        why: "The ring is what decouples the socket from everything slower without letting the decoupling become unbounded, sized for burst rather than average throughput. It is bounded so that a stalled normaliser produces a defined outcome rather than growing memory until the process dies.",
        numbers: [],
        breaks: "If the handler ever waits on a full ring instead of shedding, the block propagates to the socket and the kernel buffer starts dropping multicast packets.",
      },
    },
    {
      id: "e7",
      from: "order-gateway",
      to: "normaliser",
      tier: "data",
      label: "order / cancel, lossless",
      detail: {
        what: "Accepted order flow joining the same canonical path as market data, so both classes end up in one sequence space.",
        why: "Order flow and ticks must be totally ordered against each other, because an order matching against a book depends on which ticks preceded it. They share the path but never the overload policy.",
        numbers: ["cancels dominate order flow 10-20x fills"],
        breaks: "Any code path that treats these events like ticks, conflation especially, silently loses a trade rather than shedding a redundant snapshot.",
      },
    },
    {
      id: "e8",
      from: "normaliser",
      to: "sequencer",
      tier: "hot",
      label: "canonical events",
      detail: {
        what: "One uniform event shape arriving at the single writer, with source_ts already attached and ingest_ts stamped.",
        why: "The sequencer must be able to do its three operations without looking inside the event. Every field it would otherwise have to parse is resolved upstream, because parsing on that thread comes straight off the venue's throughput ceiling.",
        numbers: ["fixed-size packed struct, ~32B"],
        breaks: "Anything left undecoded here, an optional field or a variable-length tail, becomes work on the one thread that must stay at almost zero work per message.",
      },
    },
    {
      id: "e9",
      from: "sequencer",
      to: "ordered-ring",
      fromSide: "bottom",
      toSide: "top",
      tier: "hot",
      label: "seq stamped, claim slot",
      detail: {
        what: "The event written into a claimed ring slot carrying its monotonic sequence number, after which consumers advance their own cursors independently.",
        why: "Single writer means claiming a slot needs no lock and no CAS contention, and it removes any ambiguity about which of two near-simultaneous events came first. That decision is made exactly once here and inherited as fact by everything downstream.",
        numbers: ["hand-off in under 1µs, no copy"],
        breaks: "This pipeline has no second chance at ordering: get it wrong here and every consumer, replay and audit inherits the wrong answer with no way to detect it.",
      },
    },
    {
      id: "e10",
      from: "sequencer",
      to: "journal",
      tier: "data",
      label: "sequential append",
      detail: {
        what: "Each sequenced event appended to the durable log, in sequence order, on the same thread that assigned the number.",
        why: "The journal is the source of truth for both replay and the hot standby, and it has to be written by the writer that owns the order, or the durable record and the published order could diverge.",
        numbers: ["append at up to 2M events/s", "RPO zero for anything journalled before ack"],
        breaks: "Any per-event work here that is not a pure sequential append, an fsync per message or an index update, becomes the pipeline's real throughput ceiling rather than the sequencer itself.",
      },
    },
    {
      id: "e11",
      from: "ordered-ring",
      to: "dispatch",
      tier: "hot",
      label: "batched drain",
      detail: {
        what: "The dispatcher taking everything available on the ring in one pass rather than one message at a time.",
        why: "Batching is where most of the throughput comes from: the per-message cost of cursor reads and cache misses is amortised across the whole batch, and the batch size grows automatically exactly when the system is busiest.",
        numbers: ["ring depth alarms at 50%, ~250 ms of headroom at peak"],
        breaks: "Queue depth here should sit near zero in steady state; a depth that stays high means the shards are the bottleneck and the overload rule is about to be exercised.",
      },
    },
    {
      id: "e12",
      from: "dispatch",
      to: "conflation",
      tier: "data",
      label: "TICK, shard behind",
      detail: {
        what: "A market-data tick diverted into the per-instrument latest-value slot when its target shard cannot keep up.",
        why: "This is the overwrite half of the rule. Ticks are state you replace, so the correct response to a lagging consumer is to bin the stale intermediates and keep the freshest, not to queue deeper. The conflation rate per instrument is the metric that tracks it, and it rises under load by design.",
        numbers: [],
        breaks: "A conflation rate that spikes is the early warning that a shard is falling behind, and it is the only signal you get before the ring depth alarm fires.",
      },
    },
    {
      id: "e13",
      from: "conflation",
      to: "shards",
      tier: "data",
      label: "latest tick only",
      detail: {
        what: "The freshest tick per instrument delivered when the shard is ready to take it, with the intermediates already discarded.",
        why: "The consumer sees a correct current price and never a backlog of prices nobody will act on. Load sheds without any message class that matters being touched.",
        numbers: ["one slot per instrument"],
        breaks: "Anything downstream that needs every intermediate tick, tape reconstruction or surveillance, cannot use this stream and has to read the journal instead.",
      },
    },
    {
      id: "e14",
      from: "dispatch",
      to: "shards",
      tier: "hot",
      label: "hash(instrumentId) % N",
      detail: {
        what: "The main fan-out: each event routed to the single shard owning its instrument, in the sequence order it was stamped with, carrying the per-instrument stale flag set upstream by arbitration whenever a gap on that instrument's feed is still open.",
        why: "Partitioning rather than balancing. Ordering only has to hold within a book, so the same instrument always landing on the same consumer is what turns one total order into N independent ordered streams with no coordination. The stale flag rides in the event itself rather than a side channel, because a book you know is missing messages is worse than no book, and downstream must never silently inherit one it cannot tell is wrong.",
        numbers: ["~10k instruments across the shard set", "200 msg/s per instrument average, heavily skewed", "staleness is per instrument, never global across ~10k"],
        breaks: "Rebalancing shards moves instruments between consumers, and an event in flight during the move can arrive at the new owner behind one the old owner already applied. Making staleness global for convenience would also blind the other 9,999 instruments over a hole in one symbol, a far larger outage than the gap itself.",
      },
    },
    {
      id: "e15",
      from: "dispatch",
      to: "order-gateway",
      tier: "control",
      label: "busy: backpressure",
      detail: {
        what: "The accumulate half of the rule: order flow that cannot be absorbed causes the producer to be slowed or the client to be rejected explicitly, never silently dropped.",
        why: "An order is state that accumulates, so the sender has to learn that it did not make it. An explicit reject is a visible failure a client can handle; a silent drop is a trade that both sides believe happened differently. The nack rate alerts on any sustained non-zero value.",
        numbers: [],
        breaks: "Backpressure penalises everyone sharing that producer connection, which is why the quota lives per participant at the gateway rather than as one global valve.",
      },
    },
    {
      id: "e17",
      from: "journal",
      to: "shards",
      fromSide: "right",
      toSide: "top",
      tier: "control",
      label: "replay from snapshot seq",
      detail: {
        what: "Recovery: a restarted or promoted consumer loads its newest snapshot and replays the sequenced log forward from that snapshot's sequence number.",
        why: "Snapshot plus log is the entire recovery story, and it is the same mechanism a hot standby runs continuously, which is why failover is a promotion rather than a rebuild. Sequential replay reads far faster than line rate.",
        numbers: ["at most 30s of replay at a 30s snapshot cadence"],
        breaks: "Replay only reproduces the original if the processing path is deterministic, so a byte-for-byte replay equality check belongs in CI; determinism regressions stay silent until the day you actually need to recover.",
      },
    },
    {
      id: "e18",
      from: "shards",
      to: "matching-cores",
      tier: "hot",
      label: "in seq order, to matching",
      detail: {
        what: "The hand-off that ends this pipeline: ordered per-instrument events delivered to the matching core that owns that book.",
        why: "This boundary exists on purpose. Everything upstream exists to make this one delivery safe: gap-free, in order, and flagged if the book behind it is not trustworthy.",
        numbers: ["p99 ingest to dispatch in tens of µs"],
        breaks: "Order flow arriving for a stale instrument must be rejected here rather than matched, because matching against a book you know is incomplete produces an execution nobody can undo.",
      },
    },
  ],
};
